package com.ipons.remotedatasource.exception

enum class ErrorType {
    ENCRYPTION,
    CONNECTIVITY_ERROR,
    EMPTY_DATA,
    UNEXPECTED,
    UNAUTHORIZED,
    GEOBLOKED,
    SUBSCRIPTION_NEEDED,
    CONFLICT,
    FORBIDEN,
    PLATFORM_LICENSE,
    UNREGISTERED,
    PROXY_DETECTION,
    LIMIT_SESSIONS,
    BILLING,
    PURCHASE_CANCEL
}